openapi: 3.0.3
info:
  title: Warehouse Inventory API
  version: 1.0.0
servers:
  - url: https://Warehouse-Automation.azurewebsites.net/api/

paths:
  /shippers/{shipperId}/received-items:
    get:
      summary: Get received items for a shipper
      parameters:
        - name: shipperId
          in: path
          description: ID of the shipper
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReceivedItem'
        '400':
          description: Invalid ID supplied
        '404':
          description: Sahipper not found
    post:
      summary: Add a new received item for a shipper
      requestBody:
        description: The received item to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReceivedItem'
      parameters:
        - name: shipperId
          in: path
          description: ID of the shipper
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Received items added
        '405':
          description: Invalid input

components:
  schemas:
    ReceivedItem:
      type: object
      properties:
        Date:
          type: string
          format: date-time
          description: Date the item was received
        WarehouseID:
          type: string
          description: ID of the warehouse where the items were received
        ShippingPO:
          type: string
        ShippingID:
          type: integer
          description: ID of the shipment
        BoxesRcvd:
          type: integer
          description: Number of boxes received
